# Generated by Django 4.2 on 2023-04-12 10:37

import archive.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON-BINARY', 'non-binary')], default='MALE', max_length=15)),
                ('suspect_status', models.CharField(choices=[('MANHUNT', 'Manhunt'), ('INCARCERATED', 'incarcerated')], default='MANHUNT', max_length=100)),
                ('address_of_suspect', models.CharField(max_length=100)),
                ('crime_title', models.CharField(max_length=255)),
                ('crime_description', models.TextField()),
                ('mugshot', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1200, 630], upload_to=archive.models.cida_frs_image_archive)),
                ('date_convicted', models.DateField()),
                ('name_of_law_court', models.CharField(help_text='name of court where suspect was arraigned', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_last_seen', models.TextField(help_text='location, coordinates and other details of location where suspect was detected')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_detected', to='archive.suspect')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncodings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_face_encodings', to='archive.suspect')),
            ],
        ),
    ]
