# Generated by Django 4.2 on 2023-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
