# Generated by Django 4.2 on 2023-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_suspect_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='date_convicted',
            field=models.DateField(blank=True),
        ),
    ]
