# Generated by Django 4.2 on 2023-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_suspect_date_convicted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='nationality',
            field=models.CharField(default='Nigerian', max_length=100),
        ),
    ]
