# Generated by Django 4.2 on 2023-04-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_faceencodings_suspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencodings',
            name='face_encoding',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='faceencodings',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_face_encodings', to='archive.suspect'),
        ),
    ]
